extends: eslint:recommended

rules:
  indent: ["error", 4, { "SwitchCase": 1 }]
  semi: ["error", "always"]
  linebreak-style: ["error", "unix"]
  #max-len: ["warn", 80]
  no-var: ["error"]
  quotes: ["error", "single", "avoid-escape"]
  space-before-blocks: ["error", "always"]
  keyword-spacing: ["error", { "before": true, "after": true }]
  no-inner-declarations: ["error", "both"]
  no-loop-func: ["error"]
  constructor-super: ["error"]
  no-this-before-super: ["error"]
  #valid-jsdoc: ["warn", { "requireReturn": false }]
  spaced-comment: ["warn"]
  no-undef: ["off"]
  no-unused-vars: ["off"]
  no-console: ["error", { "allow": ["error"] }]

parserOptions:
  ecmaVersion: 9
  ecmaFeatures:
    jsx: true

env:
  browser: true
  es6: true
  webextensions: true
