language: node_js
node_js:
  - "lts/*"

dist: bionic
addons:
  apt:
    packages:
      - jq
  chrome: stable

cache:
  yarn: true
  directories:
    - "node_modules"

install:
  - yarn install
  - yarn bootstrap

script:
  - yarn build

after_success:
  - bash ./scripts/upload-coverage-to-codeclimate.sh

before_deploy:
  - mkdir -p ./build/_deploy
  - mv ./build/web-ext/mozilla/pontoon_tools-*.zip "./build/_deploy/pontoon_tools-${TRAVIS_TAG}-mozilla.zip"
  - mv ./build/web-ext/chrome/pontoon_tools-*.zip "./build/_deploy/pontoon_tools-${TRAVIS_TAG}-chrome.zip"
  - tar -cvf ./build/_deploy/docs.tar.gz ./build/docs

deploy:
  - provider: pages
    skip-cleanup: true
    local-dir: build/docs
    github-token: $GITHUB_TOKEN
    on:
      branch: master
  - provider: releases
    skip_cleanup: true
    file_glob: true
    file: build/_deploy/*
    api_key: $GITHUB_TOKEN
    on:
      branch: master
      tags: true

after_deploy:
  - yarn clean
