name: Clone and prepare
description: Clones the repository and prepares the project.

inputs:
  checkout_ref:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.checkout_ref }}
    - name: Install dependencies - cache
      id: npm_dependencies_cache
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          .npm_in_container
        key: npm-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/run-in-container.sh') }}-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          npm-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/run-in-container.sh') }}-
    - name: Install dependencies
      if: steps.npm_dependencies_cache.outputs.cache-hit != 'true' # is 'false' if restored from the 'restore-keys' fallback, see https://github.com/actions/cache#inputs
      run: make prepare_in_container
