name: Generated code is consistent

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch: # allows to be run manually
  workflow_call: # when called from another workflow
    inputs:
      checkout_ref:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.checkout_ref }}
      - name: Cache installed dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: make prepare_in_container
      - name: Generate GraphQL code
        run: make graphql_generate
      - name: Check changes in generated code
        run: |
          git status
          git diff
          UNCOMMITTED_CHANGES="$(git status --porcelain)"
          if [ -n "${UNCOMMITTED_CHANGES}" ]; then
            echo 'Found uncommitted changes' >&2
            exit 1
          fi
