name: Prepare release

on:
  workflow_dispatch: # allows to be run manually
    inputs:
      version_to_bump:
        description: 'Version to bump'
        required: true
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  ensure_default_branch:
    runs-on: ubuntu-20.04
    steps:
      - name: Stop on non-default branch
        if: github.ref != format('refs/heads/{0}', github.event.repository.default_branch)
        run: |
          echo "It's only possible to prepare a release from the default branch (${{ github.event.repository.default_branch }})." 1>&2
          exit 1
  prepare_release:
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    runs-on: ubuntu-20.04
    needs: ensure_default_branch
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Set change author
        run: |
          git config --local user.email '${{ github.actor }}@users.noreply.github.com'
          git config --local user.name '${{ github.actor }}'
      - name: Bump version
        run: npm version ${{ inputs.version_to_bump }}
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          tags: true
